name: country_phone_validator
description: A Dart package to validate phone numbers based on country codes. Retrieve country information including ISO codes and dialing codes. Ideal for applications requiring phone number validation and country-specific formatting.
version: 0.0.4
repository: https://github.com/ceto2016/country_phone_validator
# repository: https://github.com/my_org/my_repo
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

example:
  main: example/example.dart